apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: un21hwgmr-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/un21hwgmr-java-quarkus-gitops