apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: un21hwgmr-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-594982e073.dkb8.p3.openshiftapps.com/rhtap/rhtap-qe:0c498a35b643d4cb340652d13c896d38d08a3dda@sha256:70409e8a5f9c76d54733a730aa9adee07d8ab17c8ce3054957f2918e9a1c8439
        name: container-image  
